### ISSUE TITLE
Testing task list

### ISSUE THREAD

**Issue by njwilson23** [fortyninemaps/karta#20]
Need (more) tests for the following areas
- [x] skewed RegularGrids (`grid.transform[4:] != [0 0]`)
- [x] `raster.misc.hillshade`
- [x] `raster.misc.slope`
- [x] `raster.misc.aspect`
- [x] `raster.misc.grad`
- [x] `raster.misc.divergence`
- [x] `vector.shp`
- [ ] `vector.gpx`

**Comment by njwilson23** [comment]
Working on skewed grid testing in branch [skewed-grids](https://github.com/fortyninemaps/karta/tree/skewed-grids)

**Comment by njwilson23** [comment]
Closing as majority of test cases covered. Test coverage for GPX parser should be dealt with separately.
